### ISSUE TITLE
wanted: abrisco/rules_helm 

### ISSUE THREAD

**Issue by abrisco** [bazelbuild/bazel-central-registry#1048]
### Module location

https://github.com/abrisco/rules_helm

### Link to bzlmod issue in the module's repository

https://github.com/abrisco/rules_helm/issues/27

### Any other context to provide?

I'm not sure how I add this module, but I said I'd look into uploading it here. Guidance would be appreciated.

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by hobofan** [comment]
Hi @abrisco, the general way how most people publish to the BCR is via the "Publish to BCR" Github App.

As it looks like your ruleset at the core already supports bzlmod (judging by the presence and a quick glance at the contents of the MODULE.bazel file), you should be able to get the module published by completing the step in the [how-to section of the app](https://github.com/bazel-contrib/publish-to-bcr#how-it-works).

**Comment by abrisco** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1322 should conclude this!
