### ISSUE TITLE
Option to ignore module overrides in deps

### ISSUE THREAD

**Issue by pjk25** [bazelbuild/bazel-central-registry#112]
Particularly at this stage when testing bzlmod, it's common in my experience to make liberal use of the various `bazel_dep` overrides, like `archive_override`. It would great to allow the build to just ignore or warn on the overrides present in `bazel_dep`s, particularly when an override pulls in other overrides. This won't be a big deal when it's easier to provide alternate bzlmod registries, but for now it makes testing cumbersome. It is an option to use `patches` in the overrides, but then patches must exist for each step in the chain.

**Comment by Wyverald** [comment]
> This won't be a big deal when it's easier to provide alternate bzlmod registries

You can already do so with the `--registry` flag. Or do you mean something else?

> It is an option to use patches in the overrides, but then patches must exist for each step in the chain.

This is not so easy. What if two dependencies both have a dependency on some module, but provide different patches?

The best we could do is to optionally allow depending on modules with overrides (and ignore such overrides), which I assume is what your original request is.

**Comment by pjk25** [comment]
> You can already do so with the `--registry` flag. Or do you mean something else?

I meant creating and hosting a registry, though since I haven't tried it, maybe it's not difficult. For instance, RabbitMQ could benefit from having around 6 modules, some closed source, in a private registry for our builds.

> This is not so easy. What if two dependencies both have a dependency on some module, but provide different patches?

I meant that if you wanted to depend on a module B with overrides from a root module A, you could include B via and override that patches out the overrides declared in module B.

> The best we could do is to optionally allow depending on modules with overrides (and ignore such overrides), which I assume is what your original request is.

Yes, that is my original request. It would be quite helpful to have that option.

**Comment by pjk25** [comment]
Thanks @alexeagle , I'll give that a try.

**Comment by pjk25** [comment]
Forking BCR did turn out to be useful, but after additional testing, I've found that it's not enough for our use case. Essentially what would be most useful to us would be a way to have a private registry. There are some modules that I would like to reference across sub-projects in RabbitMQ, but that I wouldn't submit to BCR as they are private. Even for the public ones, I'd rather not have a long running fork of BCR.

To illustrate, here is the scenario:

```
[rabbitmq-release-builder] --> [custom-plugin] --> [rules_erlang]
                          \               \             /
                           +---->  [rabbitmq-server] --/
```

where `[thing]` is a bazel module.

It doesn't seem to make sense to publish `rabbitmq-server` to BCR as it's not of utility to anyone else, same with `custom-plugin`, so currently their MODULE files use overrides. I'd like to be able to specify overrides in `rabbitmq-release-builder` at the top level that would supersede overrides in `rabbitmq-server` and `custom-plugin`. Just ignoring the overrides in those dependencies seems to me like it would be sufficient.

**Comment by meteorcloudy** [comment]
@Wyverald Yeah, I think we should just ignore the overrides in non-root modules and not throw an error.

**Comment by Wyverald** [comment]
can you host `[custom-plugin]` and `[rabbitmq-server]` in your own private registry? In case you weren't aware, the `--registry` flag can be specified multiple times so you can use multiple registries (for example, your own private registry first, followed by https://bcr.bazel.build/)

The reason we decided to error on overrides in deps instead of silently ignore them is that we *might* one day try to get overrides to work together. That is, if your dep has an override, *your* override might override their override, etc... We can't safely enable that behavior if overrides in deps are silently ignored today. But we *can* if they cause an error today.

**Comment by pjk25** [comment]
I was aware that multiple registries can be used, though I would probably have to figure out how to authenticate access. Using `git_override` makes it easy to access a private repo.
I think if ignoring the non-root overrides was an opt-in flag, then your options remain open. I can see how the presence of overrides would be indicative of non-public or dev modules, and erroring on their presence by default is reasonable.

**Comment by pjk25** [comment]
Thinking about this further, `bzlmod` doesn't seem well suited to private repos, as `source.json` doesn't seem to have a notion of authenticated access to archives?

**Comment by Wyverald** [comment]
Might be related: https://github.com/bazelbuild/bazel/issues/15286

**Comment by pjk25** [comment]
> Might be related: [bazelbuild/bazel#15286](https://github.com/bazelbuild/bazel/issues/15286)

That seems to be about registry authentication - I guess private registry support would need both, registry auth and module source auth.

**Comment by pjk25** [comment]
I suppose the workaround for registry auth is to clone a private registry to the local disk, and use it as a local directory index registry.

**Comment by pjk25** [comment]
Recently with `5.3.1`, I've noticed that it no longer seems possible to use `patches` on a `git_override` to remove any overrides declared by that module. Was this intended? Again, I think a switch to just ignore those overrides would be very useful.

**Comment by Wyverald** [comment]
Can't remember which Bazel version did this, but module overrides are ignored in deps now.
