### ISSUE TITLE
wanted:  pybind/pybind11_protobuf

### ISSUE THREAD

**Issue by phaedon** [bazelbuild/bazel-central-registry#1121]
### Module location

https://github.com/pybind/pybind11_protobuf

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by phaedon** [comment]
update: https://github.com/pybind/pybind11_protobuf/pull/149 shall add bzlmod support to the pybind11_protobuf repo and thus simplifying this feature request.

**Comment by Wyverald** [comment]
Added in https://github.com/bazelbuild/bazel-central-registry/pull/2074
