### ISSUE TITLE
wanted: re2-abseil

### ISSUE THREAD

**Issue by eklitzke** [bazelbuild/bazel-central-registry#116]
I am trying to port a personal project to use bzlmod and bazel-central-registry, and one annoyance I've found is that the version of re2 in this repo is from the `main` branch. The re2 project also maintains an `abseil` branch which adds a dependency on abseil and has additional features not present in main (for example one that I rely on a lot is that the `abseil` branch has ubiquitous support for `std::string_view` but `main` does not).

It seems reasonable to me that some people may want to use re2 without a dependency on abseil, but I'm wondering if there's a way to support the abseil branch since it adds a lot of useful functionality.

**Comment by Wyverald** [comment]
An easy way out is to have an `re2-abseil` module.

**Comment by junyer** [comment]
Versions `2023-06-02` and onwards have the Abseil dependency. (See https://groups.google.com/g/re2-dev/c/m1Hqx2cMkY0 for background.) This bug is obsolete. :)
