### ISSUE TITLE
Provide a read-only web UI

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-central-registry#117]
The registry can be searchable and present metadata using permalink URLs.

https://bcr-web-ui-hobofan.netlify.app/ is a start.

**Comment by alexeagle** [comment]
Now it's deployed at http://bazelbuild.github.io/bazel-central-registry

**Comment by meteorcloudy** [comment]
I just got approval for using https://registry.bazel.build as a custom domain for this Github Page, working on set this up!

**Comment by meteorcloudy** [comment]
This is done ;)
