### ISSUE TITLE
[Bug]: Latest grpc module version depends on yanked rules_go

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/bazel-central-registry#1180]
### What happened?

I see build errors indicating that rules_go@0.34.0 is yanked. `bazel mod graph` shows that these are coming from grpc@1.48.1, which is the latest version.

### Version

Development (host) and target OS/architectures: Linux amd64

Output of `bazel --version`: bazel 6.4.0

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

```
bazel_dep(
    name = "grpc",
    version = "1.48.1",
    repo_name = "com_github_grpc_grpc",
)
```

Language(s) and/or frameworks involved: N/A

### How to reproduce

```shell
1. Add bazel_dep for latest grpc module version
2. Attempt to build
```

### Any other information?

Note that the grpc module appears to only exist here in the registry; the underlying repository has no `MODULE.bazel` file. Hence the bug is being filed here rather than at https://github.com/grpc/grpc

**Comment by grencez** [comment]
Is this still a problem with the 1.48.1.bcr.2 version? Is it only triggered when using a certain Go-related rule?
