### ISSUE TITLE
Document the push-to-bcr Github App

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-central-registry#123]
https://github.com/apps/publish-to-bcr has been developed by the Bazel Rules SIG to make it easy to publish a project to the Bazel Central Registry. We should document and advocate its usage.

/cc @alexeagle

**Comment by alexeagle** [comment]
@kormide is working on it.

**Comment by alexeagle** [comment]
I think this is done, right @kormide ?

**Comment by kormide** [comment]
Yup
