### ISSUE TITLE
Upstream Bzlmod changes to original repositories

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-central-registry#124]
As part of https://github.com/bazelbuild/bazel-central-registry/issues/7, there were many Bazel modules checked in the BCR with custom MODULE.bazel files and patches while the original project doesn't natively support Bzlmod. To drive the Bzlmod migration in the community, we need help to upstream the MODULE.bazel files and patches back to the original repositories. 

The list of modules in the BCR that already natively supports Bazel but not yet migrated to Bzlmod are:
- [x] bazel_skylib
- [ ] protobuf
- [x] platforms
- [x] rules_proto
- [x] rules_pkg
- [x] rules_python
- [x] rules_nodejs
- [x] rules_license
- [ ] grpc
- [ ] glog
- [ ] googletest
- [ ] gflags
- [ ] upb
- [ ] c-ares
- [ ] abseil-cpp
- [ ] re2
- [ ] boringssl
- [ ] stardoc

Note that the MODULE.bazel files and patches in the BCR for them only ensure the minimal use case can work, to fully migrate those projects to Bzlmod probably requires extra work.

**Comment by alexeagle** [comment]
For anyone who'd be motivated by a payout for helping here, there's money in the https://opencollective.com/bazel-rules-authors-sig which we can turn into a bug bounty here.

**Comment by alexeagle** [comment]
Here's a start for rules_python https://github.com/bazelbuild/rules_python/pull/744

**Comment by alexeagle** [comment]
FYI I checked off rules_nodejs - I don't think it belonged on that list though, since no file for it was ever committed as part of #7. (same for rules_sass - I assume those are only needed for building some documentation site and not for the bazel binary, so they were omitted from #7 as not strictly needed for building Bazel)

**Comment by meteorcloudy** [comment]
@alexeagle Regardless of #7,  `rules_nodejs` still fits the definition of "The list of modules in the BCR that already natively supports Bazel but not yet migrated to Bzlmod", right? 
Don't you think rules_nodejs should also support Bzlmod natively giving "aspect_rules_js" still depends on it?

**Comment by alexeagle** [comment]
Sure, I was a bit too pedantic there - rules_nodejs is migrated to bzlmod already.

**Comment by Vertexwahn** [comment]
FYI: Abseil and Google Test have now a MODULE.bazel file.

PR for gflags is open since Sep 16, 2023: https://github.com/gflags/gflags/pull/353

**Comment by mering** [comment]
Should we link upstream tracking issues and PRs here as well?

protobuf: protocolbuffers/protobuf#13618
grpc: grpc/grpc#35271

**Comment by mering** [comment]
Furthermore, upb is deprecated: https://github.com/protocolbuffers/upb#readme

**Comment by Wyverald** [comment]
This issue is largely outdated -- most (if not all) of the mentioned repos now have first-class Bzlmod support. (Except c-ares, which doesn't have any Bazel files at all.)
