### ISSUE TITLE
Migrate existing modules to the new toolchain registration API

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel-central-registry#127]
See https://github.com/bazelbuild/bazel/issues/15829

This:

```bzl
module(
  name = "foo",
  version = "2.0",
  toolchains_to_register = ["@toolchain_repo//:toolchain"],
)

ext = use_extension("//:extensions.bzl", "ext")
ext.some_tag()
use_repo(ext, "toolchain_repo")
```

should become this:

```bzl
module(
  name = "foo",
  version = "2.0",
)

ext = use_extension("//:extensions.bzl", "ext")
ext.some_tag()
use_repo(ext, "toolchain_repo")
register_toolchains("@toolchain_repo//:toolchain")
```

**Comment by alexeagle** [comment]
Is there some min,max version of Bazel where both ways are supported, to allow the transition?

**Comment by meteorcloudy** [comment]
The support for the old API isn't deleted at HEAD yet (the BCR presubmit uses Bazel@HEAD), but we'll probably delete them before 6.0 cut. Since Bzlmod is still under an experimental flag, I think that should be enough?

@Wyverald Do you think we need to cherry-pick recent Bzlmod changes into 5.3?

**Comment by mattyclarkson** [comment]
> Hopefully people have been testing Bzlmod-related stuff with rolling releases (maybe we should've been clearer about that)

We've been testing across Bazel stable releases after 5.0.0.

This just broke our CI when testing against anything other than 5.3.0.

It's not a problem, we'll just drop support for 5.2.0 and below but certainly confused us for 15 minutes why the API didn't suddenly exist.

Looking forward to `bzlmod` becoming non-experimental: we _really_ like it :)

**Comment by Wyverald** [comment]
To be clear, we haven't removed the old API from HEAD yet. @meteorcloudy's change merely migrated existing modules to use the new API, which is what broke you since the new API wasn't available before. (But now that that's done, I can remove the old API)

Sorry about the inconvenience!

**Comment by meteorcloudy** [comment]
@mattyclarkson Sorry for the confusing. 
It's recommended to test Bzlmod with Bazel@HEAD, since we are making lots of improvements to it.
If you are using Bazelisk, just set `USE_BAZEL_VERSION=last_green`

**Comment by AleksanderGondek** [comment]
> Some are cherry-pickable (like this one) but the flag parsing ones are probably harder. Hopefully people have been testing Bzlmod-related stuff with rolling releases (maybe we should've been clearer about that)

That would be nice, I have been testing bzlmod with 5.3.0
