### ISSUE TITLE
wanted: google/copybara

### ISSUE THREAD

**Issue by mattnworb** [bazelbuild/bazel-central-registry#1368]
### Module location

https://github.com/google/copybara/

### Link to bzlmod issue in the module's repository

https://github.com/google/copybara/issues/220

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1703
