### ISSUE TITLE
Align registry.bazel.build style with Bazel DevSite

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-central-registry#137]
To provide better user experience, we should align the UI design of registry.bazel.build and bazel.build. However, the Bazel DevSite is not yet in its final form yet. We'll provide style guide and illustration/ icon assets when it's done.

**Comment by meteorcloudy** [comment]
FYI @hobofan @philomathing

**Comment by meteorcloudy** [comment]
Colour platte for Bazel DevSite:
```
#F8F9FA
#F1F3F4
#7EC575
#44A147
#0C713A
#1E431E
#202124
```

**Comment by meteorcloudy** [comment]
@hobofan Can you give some pointers to how to change the color of the web ui so that it matches bazel.build better?

**Comment by hobofan** [comment]
@meteorcloudy All the styling in the bcr-ui is done via TailwindCSS (and are being applied via generated CSS classes). Most of colors we use right now come from their default color palette, but there are also a few that we add additionally.

See https://tailwindcss.com/docs/customizing-colors for the general doc.
https://github.com/bazel-contrib/bcr-ui/blob/main/tailwind.config.js is where we have defined some, and more can be added

**Comment by meteorcloudy** [comment]
Cool! I'll send a PR to adjust the bzl-green color, thanks!

**Comment by alexeagle** [comment]
@meteorcloudy still plan to send that PR?

**Comment by hobofan** [comment]
@alexeagle That was https://github.com/bazel-contrib/bcr-ui/pull/33
