### ISSUE TITLE
wanted: google/fuzztest

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/bazel-central-registry#1391]
### Module location

https://github.com/google/fuzztest

### Link to bzlmod issue in the module's repository

https://github.com/google/fuzztest/issues/950

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by chandlerc** [comment]
> Duplicate of #1377?

Yeah, but some information in each that is missing from the other. Will leave up to you how you want to merge.

**Comment by udaya2899** [comment]
@fniksic @xinhaoyuan Is this in your radar? Do you have an idea when you could add fuzztest to BCR?
