### ISSUE TITLE
[Bug]: fmt 10.2.1, use of undeclared identifier 'file_buffer'

### ISSUE THREAD

**Issue by satreix** [bazelbuild/bazel-central-registry#1537]
### What happened?

Hi @Vertexwahn, thank for the effort of migrating all this modules to the BCR.

I am moving from the WORKSPACE version of **libfmt** (see PR link below) to using the fmt module from the BCR and getting the following error:

```console
$ bazel test src/cpp/hello_world/greet/...
INFO: Analyzed 2 targets (153 packages loaded, 1344 targets configured).
ERROR: external/fmt~10.2.1/BUILD.bazel:5:11: Compiling src/os.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@fmt~10.2.1//:fmt) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 26 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/fmt~10.2.1/src/os.cc:377:6: error: use of undeclared identifier 'file_buffer'
void file_buffer::grow(size_t) {
     ^
external/fmt~10.2.1/src/os.cc:381:1: error: use of undeclared identifier 'file_buffer'
file_buffer::file_buffer(cstring_view path,
^
external/fmt~10.2.1/src/os.cc:387:1: error: use of undeclared identifier 'file_buffer'
file_buffer::file_buffer(file_buffer&& other)
^
external/fmt~10.2.1/src/os.cc:387:26: error: unknown type name 'file_buffer'
file_buffer::file_buffer(file_buffer&& other)
                         ^
external/fmt~10.2.1/src/os.cc:394:1: error: use of undeclared identifier 'file_buffer'
file_buffer::~file_buffer() {
^
external/fmt~10.2.1/src/os.cc:400:10: error: redefinition of '~ostream'
ostream::~ostream() = default;
         ^
/usr/local/include/fmt/os.h:425:3: note: previous definition is here
  ~ostream() {
  ^
6 errors generated.
Use --verbose_failures to see the command lines of failed build steps.
```

It looks like the build files in the BCR for this module are not exactly the ones in fmt ([here](https://github.com/fmtlib/fmt/blob/f68f452deaa15f222c7b2eee5f41c7a9bd249793/support/bazel/BUILD.bazel#L14)). The `strip_include_prefix` attribute is not set in the BCR version. Can you explain those differences?

### Version

Development (host) and target OS/architectures: x86-64, macOS 13.6 (22G120), Xcode 15.2 (15C500b)

Output of `bazel --version`:  bazel 7.0.2

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file: fmt 10.2.1

Language(s) and/or frameworks involved: C++

### How to reproduce

This is a PR for the repro (funny enough it does not reproduce in CI):
https://github.com/satreix/everest/pull/770

Adding the second commit of this PR fixes my issue locally.

**Comment by Vertexwahn** [comment]
`#include <fmt/core.h>` should be `#include "fmt/core.h"`

**Comment by satreix** [comment]
Thanks for the swift response @Vertexwahn.

I tried changing the include style to no avail. Even with a double quote import I get the same error as above.

I tried the C++ example you provided with the same result. I then uninstalled fmt from my machine (it was indeed installed) and got another type of error:

```console
$ bazel run //:Demo
INFO: Analyzed target //:Demo (69 packages loaded, 368 targets configured).
ERROR: ~Vertexwhan/BazelDemos/intermediate/cpp/fmt/BUILD.bazel:1:10: Linking Demo failed: (Exit 1): cc_wrapper.sh failed: error executing CppLink command (from target //:Demo) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh @bazel-out/darwin_x86_64-fastbuild/bin/Demo-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld: Undefined symbols:
  fmt::v9::vprint(fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char>>), referenced from:
      _main in main.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:Demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Turns out the include style is not the issue there. I reverted to `<>` include in my project, with fmt uninstalled, and it to work.

I am a little fuzzy on the diff between `""` and `<>` include style but it look like a Bazell C++ toolchain issue and not a "this specific BCR module" issue. Skimming https://github.com/bazelbuild/bazel/issues/5391 it looks like I could setup a sysroot to avoid pulling in /usr/local/include but this looks like a lot of work and legal implications on macOS.

My issue is resolve. I am adding this to the foot guns in C++/Bazel. Thanks for the help.

(keeping this open for a few days if you want us to have a look at the issue in your demo I have above.)

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/issues/10472#issuecomment-678528743 has a workaround.

**Comment by Vertexwahn** [comment]
@satreix 

Okay. Then let's add `strip_include_prefix = "include",` to the patch file. Can you create a PR? Just copy the folder [10.2.1]( https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/fmt/10.2.1) and name the copy `10.2.1.bcr.1` and modify the patch file there (this is the common pattern to fix issues in already published modules).

The modified `add_build_file.patch` should look like this:

```
--- /dev/null
+++ BUILD.bazel
@@ -0,0 +1,16 @@
+package(default_visibility = ["//visibility:public"])
+
+licenses(["notice"])
+
+cc_library(
+    name = "fmt",
+    srcs = [
+        "src/format.cc",
+        "src/os.cc",
+    ],
+    hdrs = glob([
+        "include/fmt/*.h",
+    ]),
+    includes = ["include"],
+    strip_include_prefix = "include",  # workaround: only needed on some macOS systems (see https://github.com/bazelbuild/bazel-central-registry/issues/1537)
+)
```

Change the `presubmit.yml` from

```
build_targets: &build_targets
- '@fmt//:fmt'

platforms:
  debian10:
    build_targets: *build_targets
  macos:
    build_targets: *build_targets
  ubuntu2004:
    build_targets: *build_targets
  windows:
    build_targets: *build_targets
```

to this:

```
matrix:
  platform:
    - debian10
    - debian11
    - macos
    - macos_arm64
    - ubuntu2004
    - ubuntu2204
    - windows
  bazel: [6.x, 7.x]
tasks:
  verify_targets:
    name: Verify build targets
    platform: ${{ platform }}
    bazel: ${{ bazel }}
    build_targets:
      - '@fmt//:fmt'
```

Feel free to add yourself as a maintainer to fmt: https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/fmt/metadata.json
