### ISSUE TITLE
XZ (LZMA) Backdoor

### ISSUE THREAD

**Issue by Attempt3035** [bazelbuild/bazel-central-registry#1754]
Hey everyone, I haven't had a chance to look into it, but does anyone know if the XZ version we have here is vulnerable to the recently discovered backdoor? If so, I'll update the version and pull the old one :)

**Comment by keith** [comment]
the BCR only has 5.4.5 https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/xz, affected versions are only 5.6.0 and 5.6.1

**Comment by Attempt3035** [comment]
Legend, thank you!
