### ISSUE TITLE
[Bug]: rules_jvm_external should be marked as requiring Bazel 7

### ISSUE THREAD

**Issue by mering** [bazelbuild/bazel-central-registry#1756]
### What happened?

As `rules_jvm_external` version 6.0 uses `use_repo_rule` which has only been introduced in Bazel 7, it should explicitly require Bazel 7 in order to show a clear and actionable error message to the user.

This can be done by adding `bazel_compatibility = [">=7.0.0"],` to the `module()` declaration in the `MODULE.bazel` file.

### Version

Development (host) and target OS/architectures: _all_

Output of `bazel --version`: 6.x

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file: _see description_

Language(s) and/or frameworks involved: _irrelevant_

### How to reproduce

```shell
`bazel_dep(name = "rules_jvm_external", version = "6.0")` with Bazel 6.x.
```

**Comment by fmeum** [comment]
@shs96c

**Comment by shs96c** [comment]
https://github.com/bazelbuild/rules_jvm_external/pull/1092

**Comment by shs96c** [comment]
This has [now been committed](https://github.com/bazelbuild/rules_jvm_external/commit/b07b79c3193930c9ffc7adf1e03475d560246fa7).
