### ISSUE TITLE
[Bug]: grpc 1.62.1 imports `googleapis` as bzlmod, but also does http_archive on it.

### ISSUE THREAD

**Issue by malkia** [bazelbuild/bazel-central-registry#1836]
### What happened?

I've got this to happen on my project, using the latest gRPC (1.62.1). I've noticed that some library was linked twice. Normally this would work, but this .dll links with /WHOLEARCHIVE, treating every .o (.obj) file from the .a (.lib) file as if it was linked on .o file level.

And I've noticed that somehow `googleapis` gets linked twice - once from the bzlmod, the other from the http_archive coming of grpc. That surprise me, as https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/grpc/1.62.1/patches/add_module_bazel.patch#L31 specifically does not mention it during the `use_repo` - but still it gets in https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L394 and it's not in the diff here - e.g. https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/grpc/1.62.1/patches/adopt_bzlmod.patch#L508 (you can see that it's still present)

I've made an additional patch for my project soft fork - https://github.com/malkia/opentelemetry-cpp/blob/main/bazel/grpc_deps_remove_googleapis.patch -> gets referenced here https://github.com/malkia/opentelemetry-cpp/blob/main/MODULE.bazel#L22

But maybe a new 1.62.1.bcr.1 (?) version might be good to have with it.

cc: @keith (and Big thanks for working on that!!!)

### Version

Development (host) and target OS/architectures:
Windows

Output of `bazel --version`:
7.1.1

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:
It's in the link above

Language(s) and/or frameworks involved:
C++

### How to reproduce

```shell
Hard to tell, but probably not needed, but I can add these steps to show it.
```

**Comment by keith** [comment]
++ we should add a new release that only has the 1. originally the problem was since these have a circular dependency they had to be added before they could use each other directly

**Comment by Wyverald** [comment]
Latest versions of grpc no longer bring in `googleapis` via a module extension (see https://github.com/bazelbuild/bazel-central-registry/blob/d770320fe8c51a0c301b6d027f69962b202f5d5e/modules/grpc/1.65.0/patches/adopt_bzlmod.patch#L225)
