### ISSUE TITLE
[Bug]: rules_proto incorrectly marks rules_cc as a dev dependency

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/bazel-central-registry#1927]
### What happened?

```
error loading package '@@rules_proto~//tools/file_concat': Unable to find package for @@[unknown repo 'rules_cc' requested from @@rules_proto~]//cc:defs.bzl: The repository '@@[unknown repo 'rules_cc' requested from @@rules_proto~]' could not be resolved: No repository visible as '@rules_cc' from repository '@@rules_proto~'.
```

### Version

Development (host) and target OS/architectures: Linux x64 as host and target

Output of `bazel --version`: bazel 7.1.0

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

```
bazel_dep(
    name = "rules_proto",
    version = "6.0.0",
)
bazel_dep(
    name = "rules_cc",
    version = "0.0.9",
)
```

Language(s) and/or frameworks involved: protobuf, C++

### Any other information?

See https://github.com/bazelbuild/rules_proto/issues/203

**Comment by alexeagle** [comment]
https://github.com/bazelbuild/rules_proto/issues/203 is the right place to report it, the registry is just a mirror.
