### ISSUE TITLE
wanted: jmillikin/rules_{bison, m4, flex}

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/bazel-central-registry#204]
We are currently transitioning our (now deprecated) [`bazel-eomii-registry`](https://github.com/eomii/bazel-eomii-registry-deprecated) to become a fork of the `bazel-central-registry`. We want to upstream the modules that are not reliant on our [`rules_ll`](https://github.com/eomii/rules_ll) to this repo, since I believe they would be useful for more users.

The repos [`rules_m4`](https://github.com/jmillikin/rules_m4), [`rules_flex`](https://github.com/jmillikin/rules_flex) and [`rules_bison`](https://github.com/jmillikin/rules_m4) are essentially always used together, so I'm tracking progress for all three here. I intend to first add some proper testing that our original module files lacked. Then I'll submit the patched variants to this repo and then upstream the patches to the original repos.

The repos in question are for instance used by [carbon](https://github.com/carbon-language/carbon-lang) and will in general likely be used by Bazel projects implementing programming languages. We also have a module for Carbon itself (very experimental, [here](https://github.com/eomii/bazel-eomii-registry-deprecated/tree/main/modules/carbon)), but testing that will likely not be straightforward and Carbon is IMO too unstable to become a module for now.

**Comment by jsharpe** [comment]
@meteorcloudy this issue can be closed now I think - the 3 modules are now in the registry.
