### ISSUE TITLE
[Bug]: inconsistent version between search page and module page

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/bazel-central-registry#2222]
### What happened?

When searching for `rules_proto` I see the expected version `6.0.0.bcr1` on the search page: https://registry.bazel.build/search?q=rules_proto

However, when I then click into that module I instead see an unexpected version `6.0.0` by default: https://registry.bazel.build/modules/rules_proto

I can still find the expected version by clicking `Show all 7 versions` and then manually selecting the correct version which is at the bottom of the list.

### Version

This is a web UI issue only. It is visible on bazel central registry: https://registry.bazel.build/

**Comment by Wyverald** [comment]
Dupe of https://github.com/bazel-contrib/bcr-ui/issues/142
