### ISSUE TITLE
[Bug]: cannot use `grpc` and `googleapis` with address sanitizer

### ISSUE THREAD

**Issue by coryan** [bazelbuild/bazel-central-registry#2334]
### What happened?

Running a test with address sanitizer which includes gRPC and googleapis results in ODR violations.  It is unclear if this is a problem with the BCR modules for googleapis, for gRPC, or the problems are in the underlying code.

### Version

Development (host) and target OS/architectures:

Linux, targeting Linux on x86.

Output of `bazel --version`:

```
bazel 7.2.1
```

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

C++

### How to reproduce

```shell
# Extract the attached tarball:
tar -zxvf bzlmod-odr.tar.gz

# If docker is available, this will install a toolchain and test the code:
docker buildx build bzlmod-odr

# If you prefer to install things manually:
cd bzlmod-odr
bazel test --test_output=errors --config asan :hello
```

### Any other information?

[bzlmod-odr.tar.gz](https://github.com/user-attachments/files/16042132/bzlmod-odr.tar.gz)

**Comment by coryan** [comment]
Maybe this is the root cause: https://github.com/grpc/grpc/issues/36983

**Comment by keith** [comment]
can you post the specific error? i think there might be an error here where grpc is vendoring googleapis and googleapis is coming from the BCR, it might be that one, which we should fix if so

**Comment by keith** [comment]
yea this looks like the case i was thinking, there are 2 versions of googleapis in the build

**Comment by coryan** [comment]
> yea this looks like the case i was thinking, there are 2 versions of googleapis in the build

Is this a problem with my test project? Meaning, should I fix the `MODULE.bazel` file or any of the other files in my repro?  Or is the problem in BCR and/or the packages themselves?

**Comment by keith** [comment]
no it's a problem in the grpc MODULE.bazel, it should move from a non-bzlmod googleapis to the bcr version
