### ISSUE TITLE
[Bug]: Cannot use `bazel vendor` with `grpc` module

### ISSUE THREAD

**Issue by coryan** [bazelbuild/bazel-central-registry#2406]
### What happened?

I tried to use `bazel vendor` and got an error:

```
ERROR: in tag at https://bcr.bazel.build/modules/grpc-java/1.62.2/MODULE.bazel:89:15: no repository visible as '@com_google_protobuf_javalite' to the repository '@@grpc-java~', but referenced by label '@com_google_protobuf_javalite//:protobuf_javalite' in attribute 'target' of tag 'override'. Is the module 'grpc-java' missing a bazel_dep or use_repo(..., "com_google_protobuf_javalite")?
    Fetching module extension maven in @@rules_jvm_external~//:extensions.bzl; starting
```

### Version

Development (host) and target OS/architectures:

Linux.

Output of `bazel --version`:

```
coryan@corws:~/repros/bzlmod-vendor$ bazel --version
bazel 7.2.1
```

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

```
bazel_dep(name = "rules_cc", version = "0.0.9")
bazel_dep(name = "grpc", version = "1.63.1.bcr.1")
```

Language(s) and/or frameworks involved:

C++

### How to reproduce

```shell
Create a small MODULE.bazel file

# cat MODULE.bazel
"""Repro a problem with `bazel vendor` and gRPC."""

module(name = "bzlmod-vendor")

bazel_dep(name = "rules_cc", version = "0.0.9")
bazel_dep(name = "grpc", version = "1.63.1.bcr.1")
------

And then try to use it:

# bazel vendor --vendor_dir=vendor
```

**Comment by coryan** [comment]
FWIW, `bazel vendor` seems to work well with the development version of Bazel:

```
USE_BAZEL_VERSION=last_green bazelisk vendor --vendor_dir=/tmp/vendor //:all //generator/... //docfx/...
```

However, `bazel mod deps` remains broken:

```
USE_BAZEL_VERSION=last_green bazelisk mod deps //:all
ERROR: in tag at https://bcr.bazel.build/modules/grpc-java/1.62.2/MODULE.bazel:89:15: no repository visible as '@com_google_protobuf_javalite' to the repository '@@grpc-java~', but referenced by label '@com_google_protobuf_javalite//:protobuf_javalite' in attribute 'target' of tag 'override'. Is the module 'grpc-java' missing a bazel_dep or use_repo(..., "com_google_protobuf_javalite")?. Type 'bazel help mod' for syntax and help.
```

**Comment by Wyverald** [comment]
> FWIW, `bazel vendor` seems to work well with the development version of Bazel:

The `vendor` command is still somewhat experimental; so it's expected that older versions of it might be broken. We'll try to "officially" launch the `vendor` command in 7.3.0.

> However, `bazel mod deps` remains broken:

grpc-java version 1.62.2 has a bug (missing a `use_repo` declaration). `bazel mod deps` runs all extensions, which unearths this bug. It has been fixed in 1.64.0.

**Comment by coryan** [comment]
Shouldn't `grpc` be fixed to refer to a non-buggy version of `grpc-java`?  Or maybe it should not use `grpc-java` at all?  It is not clear to me that it needs it.  

And shouldn't you yank `grpc-java` 1.62.2 then?

**Comment by Wyverald** [comment]
> Shouldn't `grpc` be fixed to refer to a non-buggy version of `grpc-java`?

I believe the dependency comes transitively from `googleapis`, which indeed needs fixing. I'm working on it right now.



> And shouldn't you yank `grpc-java` 1.62.2 then?

We normally only yank module versions that have security vulnerabilities, or are just outright unusable. Having a bug does not immediately warrant yanking. (Plus, yanking 1.62.2 would just mean you'd get an error message saying it was yanked; you'd still need to introduce a higher version of it into your dep graph to build successfully.)

**Comment by coryan** [comment]
> > And shouldn't you yank `grpc-java` 1.62.2 then?
> 
> We normally only yank module versions that have security vulnerabilities, or are just outright unusable. Having a bug does not immediately warrant yanking. (Plus, yanking 1.62.2 would just mean you'd get an error message saying it was yanked; you'd still need to introduce a higher version of it into your dep graph to build successfully.)

Ah, that makes sense.  Thanks for taking the time to explain.


> > Shouldn't `grpc` be fixed to refer to a non-buggy version of `grpc-java`?
> 
> I believe the dependency comes transitively from `googleapis`, which indeed needs fixing. I'm working on it right now.
> 

FWIW, I was able to override `googleapis` in [google-cloud-cpp](https://github.com/googlapis/google-cloud-cpp) to use a much smaller `MODULE.bazel`  patch and fewer dependencies:

https://github.com/googleapis/google-cloud-cpp/blob/8c9b8525fdab9a48b45d93292b5ca2b84605fee3/bazel/googleapis.modules.patch#L29-L48

Though I realize that may not work in the context of BCR.
