### ISSUE TITLE
[Bug]: no such package '@@spdlog~//': BUILD file not found in directory '' of external repository @@spdlog~.

### ISSUE THREAD

**Issue by codingl2k1** [bazelbuild/bazel-central-registry#2431]
### What happened?

Expect the spdlog dep works well, however when I use `deps = ["@spdlog//:spdlog"]` in a cc_library, bazel raises an error:
```
ERROR: no such package '@@spdlog~//': BUILD file not found in directory '' of external repository @@spdlog~. Add a BUILD file to a directory to mark it as a package.
```
Other deps works well, only the spdlog does not work.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Language(s) and/or frameworks involved:
bazel --version
bazel 7.1.2-homebrew

Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:

bazel_dep(name = "spdlog", version = "1.14.1")

**Comment by Wyverald** [comment]
spdlog 1.14.0+ uses overlays, which are only supported in Bazel 7.2.1+. We should actually have marked it with `bazel_compatibility`, but it's a bit late for that.
