### ISSUE TITLE
wanted: bazelbuild/rules_docker

### ISSUE THREAD

**Issue by rverma-dev** [bazelbuild/bazel-central-registry#262]
Can we add https://github.com/bazelbuild/rules_docker to the registry too?

**Comment by meteorcloudy** [comment]
Can you file this issue to the rules_docker repository? Apparently, they are still stuck with Bazel 4.0 (https://github.com/bazelbuild/rules_docker/blob/master/.bazelci/presubmit.yml#L6), which doesn't even support the experimental version of Bzlmod.

**Comment by uhthomas** [comment]
https://github.com/bazelbuild/rules_docker/issues/2116

**Comment by BrianEdmonds** [comment]
There does not seem to be a lot of enthusiastic motion in the rules_docker repo. I've tried switching one of my projects to rules_oci, which is already in BCR, and found it worked fine. Perhaps it would be a better use of time to work on adding any missing support to rules_oci, and providing better transition documentation?

**Comment by Wyverald** [comment]
rules_docker is archived already and the GitHub page points to rules_oci. So I'd say we can just close this.
