### ISSUE TITLE
wanted: glew

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel-central-registry#3177]
### Module location

https://glew.sourceforge.net/

### Any other context to provide?

glew is an OpenGL Extension Wrangler Library used in a lot of applications doing 3D graphics

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by hofbi** [comment]
Is https://registry.bazel.build/modules/glew not what you are looking for?
