### ISSUE TITLE
wanted: openssl/openssl

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel-central-registry#3195]
### Module location

openssl

### Any other context to provide?

It seems like many modules in the registry would benefit from having openssl available directly instead of having to use BoringSSL 

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by korDen** [comment]
Added in https://github.com/bazelbuild/bazel-central-registry/pull/3304
