### ISSUE TITLE
wanted: bazelbuild/rules_rust

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/bazel-central-registry#329]
### Module location

https://github.com/bazelbuild/rules_rust

### Link to bzlmod issue in the module's repository

https://github.com/bazelbuild/rules_rust/issues/1493

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_rust/issues/1493

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/2453
