### ISSUE TITLE
fmt Bazel support

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel-central-registry#337]
I bazelized fmt -> https://vertexwahn.de/2022/09/27/bazelizingfmtlib/

fmt is now also part of this bazel-central-registry. Maybe it makes sense to make use of  https://github.com/fmtlib/fmt/blob/master/support/bazel/BUILD.bazel and not creating an own build file via a patch.

**Comment by meteorcloudy** [comment]
/cc @mihaimaruseac 

> To get [Bazel](https://bazel.build/) working with {fmt} you can copy the files BUILD.bazel, WORKSPACE.bazel, .bazelrc, and .bazelversion from this folder (support/bazel) to the root folder of this project.

Is it possible to move those files to the root directory in the upstream repo? Otherwise, we still need a patch in the BCR.

**Comment by Vertexwahn** [comment]
{fmt} maintainers do not want to have those files in the root dir... unfortunately...  (@vitaut)

**Comment by alexeagle** [comment]
it feels to me like an OSS project is only going to be willing to spend effort on the build system that they use themselves (e.g. adding some tests that prevent them from making changes that break the Bazel build)
so unless they are actually considering switching to Bazel the answer is to follow the typical pattern here and maintain the BUILD file independenty from the project.

**Comment by vitaut** [comment]
I don't think putting build configs for anything other than the main build system (which is CMake for {fmt}) in the top-level directory is a good idea. If limitations of the build system don't allow putting configs in a subdirectory then I suggest creating a separate repo and having {fmt} a submodule.

**Comment by jsharpe** [comment]
I don't think this issue should have `module wanted` on it - `fmt` already exists in the registry; this issue is about upstreaming the bazel build files to the `fmt` project.

**Comment by alexeagle** [comment]
Ah, well I'm not even sure it makes sense to have issues on this repo which aren't resolvable by making changes to this repo. I think we ought to close it and you could have an issue on the fmt repo about accepting contributions, WDYT?

**Comment by Vertexwahn** [comment]
I closed this issue - just wanted to point out that I maintain https://github.com/fmtlib/fmt/blob/master/support/bazel/BUILD.bazel - if there are any changes in {fmt} I will try to adapt it
