### ISSUE TITLE
wanted: bazelbuild/rules_k8s

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel-central-registry#381]
### Module location

bazelbuild/rules_k8s

### Link to bzlmod issue in the module's repository

https://github.com/bazelbuild/rules_k8s/issues/711

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by hobofan** [comment]
I think this can be closed, as the repo in question has been archived, and I doubt any external maintainer will make an effort to maintain a bzlmod module for it.
