### ISSUE TITLE
wanted: bazel_skylib_gazelle_plugin

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-central-registry#397]
### Module location

https://github.com/bazelbuild/bazel-skylib/tree/main/gazelle

### Link to bzlmod issue in the module's repository

https://github.com/bazelbuild/bazel-skylib/pull/424#issuecomment-1400779445

### Any other context to provide?

Many rulesets depend on this to keep `bzl_library` targets up-to-date, including the rules-template https://github.com/bazel-contrib/rules-template/blob/0bcaef52fda3e7bcfd8d294fd1a82e5a23a9ad02/BUILD.bazel#L6

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by cgrindel** [comment]
I think that we can close this as [a module for the plugin](https://registry.bazel.build/modules/bazel_skylib_gazelle_plugin) now seems to exist.
