### ISSUE TITLE
wanted: ash2k/bazel-tools

### ISSUE THREAD

**Issue by kormide** [bazelbuild/bazel-central-registry#419]
### Module location

https://github.com/ash2k/bazel-tools

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by ash2k** [comment]
FYI I've archived the repo. I only used `rules_multirun` from it and there is a fork of them in BCR now.
