### ISSUE TITLE
Use bzlmod itself for dependencies of the Python scripts (e.g. add_module.py)

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel-central-registry#46]
The helper script has a dependency on colorama but this is not documented in the instructions. Is it worth providing a requirements.txt file for this?
Could this be automated by making the helper script a bazel target in this repo so consumers can just do `bazel run //tools:add_module`?

**Comment by shs96c** [comment]
A `bazel run` target would be ideal, and show that the tooling we're building is sufficient to do productive work.
