### ISSUE TITLE
[Bug]: ./tools/calc_integrity.py will produce a error "No module named 'validators'"

### ISSUE THREAD

**Issue by wondfor** [bazelbuild/bazel-central-registry#478]
### What happened?

root@9f8374b068e3:~/wondfor/bazel-central-registry# ./tools/calc_integrity.py https://cmc-hgh-artifactory.cmc.tools.huawei.com/artifactory/opensource_general/abseil-cpp/20211102.0/package/abseil-cpp-20211102.0.zip
Traceback (most recent call last):
  File "./tools/calc_integrity.py", line 17, in <module>
    import validators
ModuleNotFoundError: No module named 'validators'

### Version

Development (host) and target OS/architectures:
linux ubuntu 20.04
Output of `bazel --version`:
bazel 5.3.0
Version of relevant rules from the `WORKSPACE` or `MODULE.bazel` file:
bcr tools
Language(s) and/or frameworks involved:
NA

### How to reproduce

```shell
Calculate integrity value of a local file or a file downloaded at a URL.

$ ./tools/calc_integrity.py https://github.com/madler/zlib/archive/refs/tags/v1.2.13.zip
sha256-woVpUbvzDjCGGs43ZVldhroT8s8BJ52QH2xiJYxX9P8=
```

**Comment by alexeagle** [comment]
Looks like you have to manually `pip install` the package https://pypi.org/project/validators/ to get that program to run.

After https://github.com/bazelbuild/bazel-central-registry/pull/416 it will be more hermetic.

**Comment by wondfor** [comment]
> Looks like you have to manually `pip install` the package https://pypi.org/project/validators/ to get that program to run.
> 
> After #416 it will be more hermetic.
ok，got it
