### ISSUE TITLE
wanted: bazelbuild/rules_kotlin

### ISSUE THREAD

**Issue by davireis** [bazelbuild/bazel-central-registry#529]
### Module location

https://github.com/bazelbuild/rules_kotlin

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by alexeagle** [comment]
Blocking #320 according to the thread there.

**Comment by alexeagle** [comment]
Seems like there was a false start in https://github.com/bazelbuild/rules_kotlin/pull/878

**Comment by fmeum** [comment]
rules_kotlin is in the BCR now.
