### ISSUE TITLE
wanted: bazelbuild/rules_dotnet

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-central-registry#545]
### Module location

https://github.com/bazelbuild/rules_dotnet

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1757
