### ISSUE TITLE
No documentation for how to iteratively develop modules

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel-central-registry#56]
There is no documentation for how to develop modules linked to from this repo. Could there please be a link to _something_ to help people adopt `bzlmod`?

For reference, the process seems to be:

1. Create a clone of the registry
2. Add your ruleset to that using `./tools/add_module.py`
3. Point to the `file` URI of the registry in a project that uses the ruleset 
4. Realise that you need to make a change to the ruleset
5. Make the change, push to a remote fork of the ruleset
5. "Somehow" recalculate the `integrity` SHA and update that in the registry clone
6. Rebuild the project
7. Realise that you need to run `bazel shutdown` first, then rebuild the project

Is this actually the process to  follow, or is that a local workflow that can be followed to allow one to use the ruleset "in place" (as `--override_repository` allows when using rulesets via the workspace)?

**Comment by Wyverald** [comment]
Could you describe what you're actually trying to do? _Why_ do you want to "iteratively develop modules linked to from this repo"? I would expect most rules maintainers to keep developing / iterating their projects as they normally would, and then look at adding it to the registry.

**Comment by shs96c** [comment]
I'm new to module development, and I'm attempting to migrate `rules_jvm_external`'s `maven_install` from something that's run in the workspace to be modularised. I have "`project`" that depends on the `rules_jvm_external` module, but I need to keep making changes to `rules_jvm_external` as I'm developing the feature.

**Comment by Wyverald** [comment]
Closing in favor of https://github.com/bazelbuild/bazel/issues/14552
