### ISSUE TITLE
No tooling for updating the "integrity" field of `source.json`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel-central-registry#57]
When developing modules, it's useful to be able to make iterative changes without doing a full release of a ruleset. In order to do this, the `integrity` field must be recalculated. How to do this needs to be automated or documented.

**Comment by shs96c** [comment]
For reference, the key appears to be a base64 encoded version of the sha256 of the archive to download.

**Comment by Wyverald** [comment]
You're not supposed to develop modules using the registry. On the contrary, you should develop your project as you normally would, and when it's released, add it to the registry.

For the record, the `integrity` field follows the [subresource integrity metadata format](https://w3c.github.io/webappsec-subresource-integrity/#integrity-metadata-description), as is documented in the [Bzlmod user guide](https://docs.bazel.build/versions/main/bzlmod.html#index-registry). We could look at making that information more easily discoverable.

**Comment by shs96c** [comment]
I'm working on getting `rules_jvm_external` up and running with `bzlmod`, so I'm making changes in a fork of that repo, pushing to there, and then modifying a local clone of the registry so that I can try using the modularised `rules_jvm_external` in a different project.

**Comment by Wyverald** [comment]
It sounds like using an [override](https://docs.bazel.build/versions/main/bzlmod.html#modulebazel) (in particular, [`local_path_override`](https://docs.bazel.build/versions/main/skylark/lib/globals.html#local_path_override)) on `rules_jvm_external` in that different project might suit your use case much better.

**Comment by shs96c** [comment]
Can those be added on the command line, similar to `--override_repository`?

**Comment by alexeagle** [comment]
I just used `--registry=file:///path/to/bcr-fork` to do a similar workflow

**Comment by Wyverald** [comment]
Not right now, but maybe it's a good idea to add that for development? @meteorcloudy wdyt?

**Comment by meteorcloudy** [comment]
> Not right now, but maybe it's a good idea to add that for development? @meteorcloudy wdyt?

Yes, I was actually thinking about how could we run downstream test more easily (eg. to see if version 1.1 of module X breaks other modules which depend on X 1.0), if we have a flag to override a module then we don't have to mess with the MODULE.bazel file.
