### ISSUE TITLE
Ensure all archives in the BCR are guaranteed to be stable

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel-central-registry#69]
I did a quick grep of the BCR and noticed that a number of modules reference GitHub archives that are not guaranteed to be stable (see https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300 for context): 

- [x] aspect_rules_swc
- [ ] boringssl
- [x] zlib
- [x] aspect_rules_js
- [x] zstd-jni
- [x] aspect_bazel_lib
- [ ] upb

All these modules will have to be modified to be fetched from the `/archive/refs/tags/<TAG>.tar.gz` endpoint.

@Wyverald

**Comment by alexeagle** [comment]
I'd suggest a linter/CI check for this, rather than just cleaning up the existing violations.

**Comment by meteorcloudy** [comment]
Most unstable URLs have been fixed, thanks to https://github.com/bazelbuild/bazel-central-registry/pull/84

We still need to figure out what to do with upb and boringssl, see https://github.com/bazelbuild/bazel-central-registry/pull/84#issuecomment-1129320522

**Comment by fmeum** [comment]
@meteorcloudy We should probably close this issue and/or change the scope now that we learned about these URLs also not being stable.

**Comment by meteorcloudy** [comment]
Yeah, let's close this since we have already implemented check for ensuring release archive is used for future modules. We can just file new issues for migrating old ones or dealing with modules that cannot use release archives.
