### ISSUE TITLE
abseil-cpp is missing dependency on googletest?

### ISSUE THREAD

**Issue by tkoeppe** [bazelbuild/bazel-central-registry#76]
When importing abseil-cpp, I get the following error:

```[...]/external/abseil-cpp.20210324.2/absl/hash/BUILD.bazel:54:11: no such package '@com_google_googletest//': The repository '@com_google_googletest' could not be resolved: Repository '@com_google_googletest' is not visible from repository '@abseil-cpp.20210324.2' and referenced by '@abseil-cpp.20210324.2//absl/hash:hash_testing'```

Is the dependency on googletest missing from https://github.com/bazelbuild/bazel-central-registry/blob/53e8c3ad84c9407df5d644fef680fe92f27e7a39/modules/abseil-cpp/20210324.2/MODULE.bazel?

**Comment by tkoeppe** [comment]
Mind you, I am _not_ buldin `@com_google_absl//...` (I renamed the import); but `@//...` -- i.e. my _own_ repo. I don't think importing an external repo should leak into the `@`-space, should it?

**Comment by tkoeppe** [comment]
Ah no, never mind! I _do_ depend on :hash_testing directly. Sorry!

**Comment by Wyverald** [comment]
Ah. This could be a "feature"-like feature that we're still missing. `:hash_testing` does look like a public API, but probably not every dependent of Abseil wants to use it, and hence they might not want a dependency on googletest at all.

Right now, Abseil either has a dependency on googletest, or doesn't; it cannot "sometimes" depend on googletest. In Cargo for example this is solved by "features" -- when adding a dependency, you can add on optional features (in this case, the "testing utils" feature of Abseil) that themselves bring in new dependencies. But this problem can be alternatively solved by splitting the feature into a separate module, so we haven't prioritized this.

So for the time being, we could either just add googletest as a dependency to Abseil, or try to split out the "testing utils" parts of Abseil into a separate module.

**Comment by grencez** [comment]
Version 20230802.0 of the abseil-cpp module introduced a googletest dependency. (Unlike google_benchmark, which was changed to a dev_dependency in the .bcr.1 patch.)

Is this issue resolved? In an acceptable way?
