### ISSUE TITLE
wanted: [toolchains_llvm]

### ISSUE THREAD

**Issue by kakisong** [bazelbuild/bazel-central-registry#937]
### Module location

https://github.com/grailbio/bazel-toolchain.git

### Fund our work

- [X] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by zaucy** [comment]
this can be closed now right? https://registry.bazel.build/modules/toolchains_llvm
